services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: irondust
      POSTGRES_USER: irondust
      POSTGRES_PASSWORD: irondust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  meili:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_MASTER_KEY: local_dev_key
    ports:
      - "7700:7700"
    volumes:
      - "./meili_data:/meili_data"
  qdrant:
    image: qdrant/qdrant:v1.9.0
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
  api:
    build: .
    environment:
      JAVA_OPTS: ""
      OPENAI_RPM: ${OPENAI_RPM:-500}
      OPENAI_TPM: ${OPENAI_TPM:-200000}
      MEILI_HOST: http://meili:7700
      MEILI_KEY: local_dev_key
      QDRANT_HOST: http://qdrant:6333
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_COLLECTION: products_vec_lg
      EMBEDDING_MODEL: text-embedding-3-large
      EMBEDDING_DIM: 3072
      HYBRID_RRF_K: 60
      HYBRID_VECTOR_K: 100
      VECTOR_TIMEOUT_MS: 150
      VECTOR_MIN_QUERY_LENGTH: 3
      QDRANT_UPSERT_BATCH: 8
      QDRANT_MAX_RETRIES: 5
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_ENRICH: ${AI_ENRICH:-true}
      AI_ALLOW_HIGH_CONF_CRITICAL: ${AI_ALLOW_HIGH_CONF_CRITICAL:-true}
      AI_CRIT_CONF_THRESHOLD: ${AI_CRIT_CONF_THRESHOLD:-0.9}
      AI_CONF_THRESHOLD_SERVINGS: ${AI_CONF_THRESHOLD_SERVINGS:-0.75}
      AI_CONF_THRESHOLD_SERVING_SIZE_G: ${AI_CONF_THRESHOLD_SERVING_SIZE_G:-0.75}
      ADMIN_BASIC_USERNAME: ${ADMIN_BASIC_USERNAME:-admin}
      ADMIN_BASIC_PASSWORD: ${ADMIN_BASIC_PASSWORD:-admin}
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/irondust
      SPRING_R2DBC_USERNAME: irondust
      SPRING_R2DBC_PASSWORD: irondust
    ports:
      - "4000:4000"
    depends_on:
      - db
      - meili
      - qdrant



volumes:
  pg_data:
