site_name: IronDust Dropshipping Search
site_description: Product enrichment and search service for irondust.eu

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: cyan

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Overview: index.md
  - Getting Started: how-to-run.md
  - Architecture: architecture.md
  - API: api.md
  - Localization: localization.md
  - Development: dev-checklist.md


