server:
  port: 4000
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

app:
  adminKey: dev_admin_key
  baseUrl: https://www.irondust.eu
  perPage: 100
  indexName: products_lex
  contentIndexName: content
  ingestParallelism: 30
  meiliConcurrentUpdates: 25
  uploadChunkSize: 10000
  ingestHistoryDir: ${INGEST_HISTORY_DIR:tmp/ingest-history}

meili:
  host: ${MEILI_HOST:http://127.0.0.1:7700}
  key: ${MEILI_KEY:local_dev_key}

vector:
  host: ${QDRANT_HOST:http://127.0.0.1:6333}
  apiKey: ${QDRANT_API_KEY:}
  collectionName: ${QDRANT_COLLECTION:products_vec_lg}
  embeddingModel: ${EMBEDDING_MODEL:text-embedding-3-large}
  embeddingDim: ${EMBEDDING_DIM:3072}
  rrfK: ${HYBRID_RRF_K:60}
  vectorSearchK: ${HYBRID_VECTOR_K:100}
  qdrantUpsertBatchSize: ${QDRANT_UPSERT_BATCH:64}
  qdrantMaxRetries: ${QDRANT_MAX_RETRIES:3}
  vectorTimeoutMs: ${VECTOR_TIMEOUT_MS:150}
  minQueryLength: ${VECTOR_MIN_QUERY_LENGTH:3}

spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://127.0.0.1:5432/irondust}
    username: ${SPRING_R2DBC_USERNAME:irondust}
    password: ${SPRING_R2DBC_PASSWORD:irondust}

logging:
  level:
    com.irondust.search.service.enrichment: DEBUG
    com.irondust.search.service.IngestService: DEBUG
    com.irondust.search.service.enrichment.AIEnricher: INFO


